### ISSUE TITLE
自动保存功能

### ISSUE THREAD

**Issue by sannere** [sannere/tale#1]
文件路径：tale/src/main/resources/static/admin/js/new_article.js

背景：这是创建文章的页面
![image](https://user-images.githubusercontent.com/35032210/51799995-ddcfca80-2263-11e9-88e0-29c950ada12a.png)
按照我现在的理解：title和content的初始值是"，当它俩都不为空时，会执行这个js文件中的autoSave函数。

我的疑问是，既然是两个值先不为空，再执行autoSave函数的功能，那么不是这个函数改变的这两个变量。可是在new.html(tale/src/main/resources/templates/admin/article/new.html)，和这个文件中，都没有找到哪里有给这两个变量赋值的地方。

实际情境感觉像是，我在浏览器的页面中把title和content写了一些东西以后，我没有点保存，也没有发布，我就是在输入框里输入了点文字，服务器不知道怎么就知道了（这就是我的问题，我想知道，浏览器应该没有主动告诉服务器我输入了内容，对吧，是服务器有个端口一直监控着这个页面，不停的发请求问浏览器，这两个input有没有内容呢，那么到底是哪个函数偷偷改了这个值），然后服务器就开启了自动保存的服务。
![image](https://user-images.githubusercontent.com/35032210/51800198-cf36e280-2266-11e9-8ec5-e5616df30031.png)

@windmemory

**Comment by windmemory** [comment]
这两个变量应该是你在浏览器里面输入的时候赋值了吧
