### ISSUE TITLE
关于markdown文本框的数据联通

### ISSUE THREAD

**Issue by sannere** [sannere/tale#2]
### 背景
是这样的，我在网页console里面想找一个功能对应的element是谁，看到了如下图，很多div嵌套的一个结构：
![image](https://user-images.githubusercontent.com/35032210/53239308-a7f0fb00-36d6-11e9-8229-e595ce28d1a7.png)

可是奇怪的是，我在html文件里找到对应id的element，结构特别简单：
```
<div id="md-container" v-show="article.fmtType == 'markdown'" class="form-group col-md-12">
        <textarea id="md-editor"></textarea>
</div>
```
***
### 我的问题是：
js是怎么加工md-container这个元素的。

### 我都做了以下的工作：
1. 我在console-network观察了网络通信，确认我在页面的文本框输入内容之后，没有向服务器发请求，那么就是js和html它们的事情，与java无关。
2. 我尝试去new_article.js和new.html文件中通过id找关联。因为网页中的me-container这个element多出来很多”填充物“，所以我就搜了md-container这个词。可是发现这个词只出现在切换文本编辑器格式那个switchEditor函数里（有两种编辑格式：一个是markdown，一个是html富文本编辑器）。但是页面最开始加载出来的时候也没有调用这个switchEditor函数，实际上，在整个new.js中，从来没有调用过这个函数，只有定义部分的代码。
3. 接着我去mditor.js(就是加载)
3. 我换了个思路，我开始搜挂载在哪部分生效，发现md-editor而不是md-container绑定到了vue的组件上，这我就更不服气了。。为什么绑定的不是它的父节点？？？

@windmemory

**Comment by sannere** [comment]
@windmemory

**Comment by windmemory** [comment]
Seems like it is using this plugin: [MDitor](https://github.com/qfish/MDitor)

**Comment by windmemory** [comment]
So the elements above the `md-editor` should be generated by the `MDitor` library.

You can find it is created inside file `src/main/resources/static/admin/js/edit_page.js`
```js
mditor = window.mditor = Mditor.fromTextarea(document.getElementById('md-editor'));
```

**Comment by sannere** [comment]
嗯，这个语句new.js里也有，但是按道理它不应该和md-editor绑定，应该是和md-container绑定哇。。。

**Comment by windmemory** [comment]
hmm，为什么呢？为什么应该和md-container绑定呢？

**Comment by windmemory** [comment]
嗯嗯，其实也是可以的

当获取到了一个dom里面的元素，通过js代码可以在这个元素的子节点或者同级甚至父节点都可以操作的

常见的vue或者react的方式都是在当前传入元素的下面创建子节点，但是只是某一个常见的方式而已

像这个`MDitor`就有点另辟蹊径了，我第一次见到这样做操作的说实话

**Comment by sannere** [comment]
ok~

**Comment by sannere** [comment]
```
<container>
   <additional> </additional> 
   <editor></editor>
</container>
```
应该是这种结构。那组件如果和editor绑定以后，能在editor外面新增一些别的element吗？
